apiVersion: k8s.nrvn.cc/v1
kind: Redis
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis-sample
    app.kubernetes.io/part-of: k8dis
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: k8dis
  name: redis-sample
spec:
  # TODO(user): Add fields here
